version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      #- run:
      #    name: Install dependencies and build project
      #    command: npm install
      - sonarcloud/scan
      - coveralls/upload
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
  coveralls: coveralls/coveralls@1.0.4

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
