version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
  coveralls: coveralls/coveralls@1.0.4

jobs:
  build:
    docker:
      - image: circleci/node:14.0
    steps:
      - checkout
      - run: npm install
      - run: npm i nyc
      - run: npm i coveralls
      - sonarcloud/scan
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm run test
      - run: # run code coverage report
          name: code-coverage
          command: npm run coveralls
      - run: # run build
          name: Build
          command: npm run build
      - coveralls/upload
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
